### ISSUE TITLE
What kernel was this compiled against?

### ISSUE THREAD

**Issue by jaketgh** [h33p/kvm-rdtsc-hack#1]
You reference 
#include <linux/kvm_types.h>
#include <linux/kvm_host.h>

However, I believe kvm_x86_ops went through a restructuring.

/home/me/code/kvm-rdtsc-hack/main.c: In function ‘vcpu_pre_run’:
/home/me/code/kvm-rdtsc-hack/main.c:71:26: error: invalid type argument of ‘->’ (have ‘struct kvm_x86_ops’)
   71 |  tsc_offset = kvm_x86_ops->read_l1_tsc_offset(vcpu);
      |                          ^~
/home/me/code/kvm-rdtsc-hack/main.c:95:39: error: invalid type argument of ‘->’ (have ‘struct kvm_x86_ops’)
   95 |    vcpu->arch.tsc_offset = kvm_x86_ops->write_l1_tsc_offset(vcpu, new_tsc_offset);
      |                                       ^~

**Comment by h33p** [comment]
This was compiled against pre-5.7. 5.7+ have unexoorted kallsyms, and there is a possibility that KVM ops have had the same fate. I will check and see if I can fix this.
